### PR TITLE
PEDS-902 Cache counts

### PR DESCRIPTION
**Pull request by grugna**
This PR is adding an application level cache to improve the retrieval time for the counts displayed on the landing page.

### CODE REVIEW

**Comment by nikoferraz** [comment]
@grugna, can you add a test for this [here](https://drive.google.com/drive/folders/1iLXcEsfECpmAzBjjhSzVp8heDpAxnj_b)?

**Comment by nikoferraz** [comment]
@grugna, did you mean to fill these out? 

New Features
Implemented XXX
Breaking Changes
Bug Fixes
Improvements
Dependency updates
Deployment changes

**Comment by grugna** [comment]
> 

We don't have any unit test implemented for pcdcanalysistools, that is a separate ticket in my list, but I haven't started working on it yet. This is not adding any functionality that can be tested. It is only adding a caching layer at the application level to speed up retrieval, but the data displayed to the user are the same as without this cache and the time of execution on an application level can vary depending on the authN and authZ time. For this reason verifying that the aggregation numbers are correct is the only test I can think of, and that is already on Rolando's list for deployment testing.

**Comment by grugna** [comment]
```
New Features
Implemented XXX
Breaking Changes
Bug Fixes
Improvements
Dependency updates
Deployment changes
```
These were added by default in the creation of the PR and I forgot to clean it up

**Review by nikoferraz — APPROVED** [review]

**Pull request merged**
